version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: check_services_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/services_health
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: check_services_db
    environment:
      POSTGRES_DB: services_health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"