spring:
  application:
    name: CheckServiceHealth
  datasource:
    url: jdbc:postgresql://192.168.238.214:5432/services_health
    password: 123
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always

  mail:
    host: smtp.mail.ru
    port: 465
    username: nik.malykh.2024@mail.ru
    password: PLmpfSCAvDhCzrtzYSiw
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

    default-encoding: UTF-8
url:
  tg:
    key: "http://localhost:9001"
  tg_req:
    key: "/notify"
  get_token:
    key: "get-token"
  check_status:
    key: "check-status"

email:
  from: "nik.malykh.2024@mail.ru"
